"""empty message

Revision ID: 0cc6c7951234
Revises: 
Create Date: 2021-03-20 21:04:55.552512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc6c7951234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('alert_level', sa.Integer(), nullable=True),
    sa.Column('alert_message', sa.String(), nullable=True),
    sa.Column('alert_status', sa.String(length=50), nullable=True),
    sa.Column('member_associated_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('template_header', sa.String(), nullable=True),
    sa.Column('template_header_default', sa.String(), nullable=True),
    sa.Column('template_content', sa.String(), nullable=True),
    sa.Column('template_content_default', sa.String(), nullable=True),
    sa.Column('template_description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('productType', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('stripe_product_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('stripe_price_fortnight_id', sa.String(), nullable=True),
    sa.Column('age_restriction', sa.Integer(), nullable=True),
    sa.Column('waiver_required', sa.Boolean(), nullable=True),
    sa.Column('name_unchangeable', sa.String(length=50), nullable=True),
    sa.Column('default_item', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('allow_anonymous_sale', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('userType', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('waiver_temp',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('middleName', sa.String(length=50), nullable=False),
    sa.Column('address1', sa.String(length=50), nullable=True),
    sa.Column('address2', sa.String(length=50), nullable=True),
    sa.Column('postalCode', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('workphone', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('emergencyContact', sa.String(length=50), nullable=True),
    sa.Column('emergencyContactPhone', sa.String(length=50), nullable=True),
    sa.Column('emergencyContactPhoneWork', sa.String(length=50), nullable=True),
    sa.Column('emergencyContactRelation', sa.String(length=50), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('signature_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiver_temp_fetch_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('fetched_amount', sa.Integer(), nullable=True),
    sa.Column('fetched_time', sa.Float(), nullable=True),
    sa.Column('server_response', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userType', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('middleName', sa.String(length=50), nullable=False),
    sa.Column('address1', sa.String(length=50), nullable=True),
    sa.Column('address2', sa.String(length=50), nullable=True),
    sa.Column('postalCode', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('cellphone', sa.String(length=50), nullable=True),
    sa.Column('homephone', sa.String(length=50), nullable=True),
    sa.Column('workphone', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('birthday_month', sa.Integer(), nullable=True),
    sa.Column('birthday_day', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('emergencyContact', sa.String(length=50), nullable=True),
    sa.Column('emergencyContactPhone', sa.String(length=50), nullable=True),
    sa.Column('emergencyContactRelation', sa.String(length=50), nullable=True),
    sa.Column('paxton_card_id', sa.String(), nullable=True),
    sa.Column('default_payment_method', sa.String(), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.Column('last_edit', sa.DateTime(), nullable=True),
    sa.Column('warning', sa.String(), nullable=True),
    sa.Column('access_after_hours', sa.Boolean(), nullable=True),
    sa.Column('waiver_signed', sa.Boolean(), nullable=True),
    sa.Column('waiver_signed_date', sa.DateTime(), nullable=True),
    sa.Column('signatureImage', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('got_to_know_channel', sa.String(length=50), nullable=True),
    sa.Column('mail_on_internal_events', sa.Boolean(), nullable=True),
    sa.Column('mail_promotions', sa.Boolean(), nullable=True),
    sa.Column('do_not_send_mail', sa.Boolean(), nullable=True),
    sa.Column('concession_passes', sa.Integer(), nullable=True),
    sa.Column('stripe_id', sa.String(length=50), nullable=True),
    sa.Column('stripe_invoice_prefix', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['family'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('notes', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('rented', sa.Integer(), nullable=True),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkin',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('checkin_member_id', sa.String(), nullable=True),
    sa.Column('checkin_type', sa.String(length=50), nullable=False),
    sa.Column('checkin_date', sa.DateTime(), nullable=True),
    sa.Column('checkin_status', sa.String(), nullable=True),
    sa.Column('checkin_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['checkin_member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('paid', sa.Integer(), nullable=False),
    sa.Column('membershipActive', sa.Boolean(), nullable=True),
    sa.Column('expected_payment_amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('billing_frequency', sa.String(length=50), nullable=True),
    sa.Column('frozen', sa.Boolean(), nullable=True),
    sa.Column('frozen_until', sa.DateTime(), nullable=True),
    sa.Column('on_holiday', sa.Boolean(), nullable=True),
    sa.Column('holiday_until', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('billingType', sa.String(length=50), nullable=True),
    sa.Column('membership_auto_renew', sa.Boolean(), nullable=True),
    sa.Column('membership_invoice_num', sa.Integer(), nullable=True),
    sa.Column('membership_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_method',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('last_four', sa.String(length=10), nullable=True),
    sa.Column('payment_method_type', sa.String(), nullable=False),
    sa.Column('payment_method_stripe_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sub_product_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('rental_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('returned_date', sa.DateTime(), nullable=True),
    sa.Column('rental_item_size', sa.String(length=50), nullable=True),
    sa.Column('rental_item_color', sa.String(length=50), nullable=True),
    sa.Column('rental_item_name', sa.String(length=50), nullable=True),
    sa.Column('returned', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['sub_product_id'], ['sub_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restock',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sub_product_id', sa.String(), nullable=False),
    sa.Column('restock_date', sa.DateTime(), nullable=True),
    sa.Column('restock_amount', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sub_product_id'], ['sub_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiver',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('effective_member', sa.String(), nullable=False),
    sa.Column('signed_member', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['effective_member'], ['member.id'], ),
    sa.ForeignKeyConstraint(['signed_member'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership_adjustment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('membership_id', sa.String(), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('new_start_date', sa.DateTime(), nullable=True),
    sa.Column('new_end_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership_invoice',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('membership_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('next_invoice_id', sa.String(length=50), nullable=True),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('stripe_price_choice', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('sub_product_id', sa.String(), nullable=True),
    sa.Column('membership_id', sa.String(), nullable=True),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('productType', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('productName', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('default_item', sa.Boolean(), nullable=True),
    sa.Column('sale_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Integer(), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_entries')
    op.drop_table('membership_invoice')
    op.drop_table('membership_adjustment')
    op.drop_table('waiver')
    op.drop_table('restock')
    op.drop_table('rental')
    op.drop_table('payment_method')
    op.drop_table('membership')
    op.drop_table('checkin')
    op.drop_table('sub_products')
    op.drop_table('member')
    op.drop_table('waiver_temp_fetch_log')
    op.drop_table('waiver_temp')
    op.drop_table('users')
    op.drop_table('revoked_tokens')
    op.drop_table('products')
    op.drop_table('family')
    op.drop_table('email_templates')
    op.drop_table('alerts')
    # ### end Alembic commands ###
